/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.card-img-top[_ngcontent-%COMP%]{\r\n    max-height: 100px;\r\n}\r\n.input-group-addon[_ngcontent-%COMP%] {\r\n    width: 80px\r\n}\r\n.input-group[_ngcontent-%COMP%] {\r\n    margin-bottom: 16px\r\n}'];